# Generated by Django 3.1.4 on 2020-12-11 20:31

import cert_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('public_num', models.URLField(default=uuid.uuid4, editable=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('status', models.BooleanField(default=False)),
                ('pdf', models.FileField(null=True, upload_to=cert_app.models.user_directory_path)),
                ('internal_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
