# Generated by Django 3.1.4 on 2020-12-14 17:53

import cert_app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=cert_app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='public_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
