# Generated by Django 3.1.4 on 2020-12-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0002_auto_20201214_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='internal_num',
            new_name='emitter',
        ),
    ]
