# Generated by Django 3.1.4 on 2020-12-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0003_auto_20201214_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='internal_num',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
