# Generated by Django 3.1.4 on 2020-12-14 22:39
1

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    certs= apps.get_model('cert_app','Certificate')
    for cert in certs.objects.all():
        cert.internal_num = uuid.uuid4()
        cert.save(update_fields=['internal_num'])


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0004_certificate_internal_num'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
        
        migrations.AlterField(
            model_name='certificate',
            name='internal_num',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True, editable=True)
        )
    ]
