# Generated by Django 3.1.4 on 2020-12-14 23:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert_app', '0005_auto_20201214_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('emitter', 'internal_num')},
        ),
    ]
