# Generated by Django 3.1.4 on 2020-12-14 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cert_app', '0006_auto_20201214_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='internal_num',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
